; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_c3_mini]
platform = espressif32
monitor_speed = 115200
board = lolin_c3_mini
build_flags = 
	-DCORE_DEBUG_LEVEL=4
framework = arduino
board_upload.flash_size = 4MB
board_build.partitions = partitions_custom.csv
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/ENS160 - Adafruit Fork@^3.0.1
	fastled/FastLED@^3.10.3
	esp32async/AsyncTCP
	esp32async/ESPAsyncWebServer

; --- Upload OTA ---
upload_protocol = espota
upload_port = cloudy-station.local
upload_flags =
    --auth=mycloudyisbetter